# Generated from buf/validate/conformance/cases/subdirectory/in_subdirectory.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.0.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import TYPE_CHECKING

from protobuf._codegen import file_desc

from .... import validate_pb

if TYPE_CHECKING:
    from protobuf import DescFile



_DESC = file_desc(
    b'\nAbuf/validate/conformance/cases/subdirectory/in_subdirectory.proto\x12+buf.validate.conformance.cases.subdirectory\x1a\x1bbuf/validate/validate.protob\x06proto3',
    [
        validate_pb.desc(),
    ],
    {
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `buf/validate/conformance/cases/subdirectory/in_subdirectory.proto`."""
    return _DESC
