# Generated from buf/validate/conformance/cases/bool.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.0.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal, TYPE_CHECKING

from protobuf import Message
from protobuf._codegen import file_desc

from ... import validate_pb

if TYPE_CHECKING:
    from protobuf import DescFile


class BoolNone(Message[Literal["val"]]):
    """
    ```proto
    message buf.validate.conformance.cases.BoolNone
    ```

    Attributes:
        val:
            ```proto
            bool val = 1;
            ```
    """

    __slots__ = ("val",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            val: bool = False,
        ) -> None:
            pass

        val: bool

class BoolConstTrue(Message[Literal["val"]]):
    """
    ```proto
    message buf.validate.conformance.cases.BoolConstTrue
    ```

    Attributes:
        val:
            ```proto
            bool val = 1;
            ```
    """

    __slots__ = ("val",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            val: bool = False,
        ) -> None:
            pass

        val: bool

class BoolConstFalse(Message[Literal["val"]]):
    """
    ```proto
    message buf.validate.conformance.cases.BoolConstFalse
    ```

    Attributes:
        val:
            ```proto
            bool val = 1;
            ```
    """

    __slots__ = ("val",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            val: bool = False,
        ) -> None:
            pass

        val: bool

class BoolExample(Message[Literal["val"]]):
    """
    ```proto
    message buf.validate.conformance.cases.BoolExample
    ```

    Attributes:
        val:
            ```proto
            bool val = 1;
            ```
    """

    __slots__ = ("val",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            val: bool = False,
        ) -> None:
            pass

        val: bool


_DESC = file_desc(
    b'\n)buf/validate/conformance/cases/bool.proto\x12\x1ebuf.validate.conformance.cases\x1a\x1bbuf/validate/validate.proto"\x1c\n\x08BoolNone\x12\x10\n\x03val\x18\x01 \x01(\x08R\x03val"*\n\rBoolConstTrue\x12\x19\n\x03val\x18\x01 \x01(\x08R\x03valB\x07\xbaH\x04j\x02\x08\x01"+\n\x0eBoolConstFalse\x12\x19\n\x03val\x18\x01 \x01(\x08R\x03valB\x07\xbaH\x04j\x02\x08\x00"(\n\x0bBoolExample\x12\x19\n\x03val\x18\x01 \x01(\x08R\x03valB\x07\xbaH\x04j\x02\x10\x01b\x06proto3',
    [
        validate_pb.desc(),
    ],
    {
        "BoolNone": BoolNone,
        "BoolConstTrue": BoolConstTrue,
        "BoolConstFalse": BoolConstFalse,
        "BoolExample": BoolExample,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `buf/validate/conformance/cases/bool.proto`."""
    return _DESC
