# Generated from buf/validate/conformance/cases/groups_proto2.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.0.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal, TYPE_CHECKING

from protobuf import Message
from protobuf._codegen import file_desc

from ... import validate_pb

if TYPE_CHECKING:
    from protobuf import DescFile


class GroupOptional(Message[Literal["optional"]]):
    """
    ```proto
    message buf.validate.conformance.cases.GroupOptional
    ```

    Attributes:
        optional:
            ```proto
            optional buf.validate.conformance.cases.GroupOptional.Optional optional = 1;
            ```
    """

    __slots__ = ("optional",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            optional: GroupOptional.Optional | None = None,
        ) -> None:
            pass

        optional: GroupOptional.Optional | None

    class Optional(Message[Literal["value"]]):
        """
        ```proto
        message buf.validate.conformance.cases.GroupOptional.Optional
        ```

        Attributes:
            value:
                ```proto
                optional string value = 1;
                ```
        """

        __slots__ = ("value",)

        if TYPE_CHECKING:

            def __init__(
                self,
                *,
                value: str | None = None,
            ) -> None:
                pass

            value: str

class GroupRepeated(Message[Literal["repeated"]]):
    """
    ```proto
    message buf.validate.conformance.cases.GroupRepeated
    ```

    Attributes:
        repeated:
            ```proto
            repeated buf.validate.conformance.cases.GroupRepeated.Repeated repeated = 1;
            ```
    """

    __slots__ = ("repeated",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            repeated: list[GroupRepeated.Repeated] | None = None,
        ) -> None:
            pass

        repeated: list[GroupRepeated.Repeated]

    class Repeated(Message[Literal["value"]]):
        """
        ```proto
        message buf.validate.conformance.cases.GroupRepeated.Repeated
        ```

        Attributes:
            value:
                ```proto
                optional int32 value = 1;
                ```
        """

        __slots__ = ("value",)

        if TYPE_CHECKING:

            def __init__(
                self,
                *,
                value: int | None = None,
            ) -> None:
                pass

            value: int

class GroupRequired(Message[Literal["required"]]):
    """
    ```proto
    message buf.validate.conformance.cases.GroupRequired
    ```

    Attributes:
        required:
            ```proto
            required buf.validate.conformance.cases.GroupRequired.Required required = 1;
            ```
    """

    __slots__ = ("required",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            required: GroupRequired.Required | None = None,
        ) -> None:
            pass

        required: GroupRequired.Required | None

    class Required(Message[Literal["value"]]):
        """
        ```proto
        message buf.validate.conformance.cases.GroupRequired.Required
        ```

        Attributes:
            value:
                ```proto
                optional bool value = 1;
                ```
        """

        __slots__ = ("value",)

        if TYPE_CHECKING:

            def __init__(
                self,
                *,
                value: bool | None = None,
            ) -> None:
                pass

            value: bool

class GroupCustom(Message[Literal["custom"]]):
    """
    ```proto
    message buf.validate.conformance.cases.GroupCustom
    ```

    Attributes:
        custom:
            ```proto
            optional buf.validate.conformance.cases.GroupCustom.Custom custom = 1;
            ```
    """

    __slots__ = ("custom",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            custom: GroupCustom.Custom | None = None,
        ) -> None:
            pass

        custom: GroupCustom.Custom | None

    class Custom(Message[Literal["value", "div"]]):
        """
        ```proto
        message buf.validate.conformance.cases.GroupCustom.Custom
        ```

        Attributes:
            value:
                ```proto
                optional int32 value = 1;
                ```
            div:
                ```proto
                optional int32 div = 2;
                ```
        """

        __slots__ = ("value", "div")

        if TYPE_CHECKING:

            def __init__(
                self,
                *,
                value: int | None = None,
                div: int | None = None,
            ) -> None:
                pass

            value: int
            div: int


_DESC = file_desc(
    b'\n2buf/validate/conformance/cases/groups_proto2.proto\x12\x1ebuf.validate.conformance.cases\x1a\x1bbuf/validate/validate.proto"\x91\x01\n\rGroupOptional\x12R\n\x08optional\x18\x01 \x01(\n26.buf.validate.conformance.cases.GroupOptional.OptionalR\x08optional\x1a,\n\x08Optional\x12 \n\x05value\x18\x01 \x01(\tR\x05valueB\n\xbaH\x07r\x05\n\x03foo"\x8e\x01\n\rGroupRepeated\x12R\n\x08repeated\x18\x01 \x03(\n26.buf.validate.conformance.cases.GroupRepeated.RepeatedR\x08repeated\x1a)\n\x08Repeated\x12\x1d\n\x05value\x18\x01 \x01(\x05R\x05valueB\x07\xbaH\x04\x1a\x02 \x00"\x8e\x01\n\rGroupRequired\x12R\n\x08required\x18\x01 \x02(\n26.buf.validate.conformance.cases.GroupRequired.RequiredR\x08required\x1a)\n\x08Required\x12\x1d\n\x05value\x18\x01 \x01(\x08R\x05valueB\x07\xbaH\x04j\x02\x08\x01"\xe1\x01\n\x0bGroupCustom\x12J\n\x06custom\x18\x01 \x01(\n22.buf.validate.conformance.cases.GroupCustom.CustomR\x06custom\x1a\x85\x01\n\x06Custom\x12\x14\n\x05value\x18\x01 \x01(\x05R\x05value\x12\x10\n\x03div\x18\x02 \x01(\x05R\x03div:S\xbaHP\x1aN\n\x10group.custom.div\x12\x1evalue must be divisible by div\x1a\x1athis.value % this.div == 0',
    [
        validate_pb.desc(),
    ],
    {
        "GroupOptional": GroupOptional,
        "GroupOptional.Optional": GroupOptional.Optional,
        "GroupRepeated": GroupRepeated,
        "GroupRepeated.Repeated": GroupRepeated.Repeated,
        "GroupRequired": GroupRequired,
        "GroupRequired.Required": GroupRequired.Required,
        "GroupCustom": GroupCustom,
        "GroupCustom.Custom": GroupCustom.Custom,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `buf/validate/conformance/cases/groups_proto2.proto`."""
    return _DESC
