# Generated from buf/validate/conformance/cases/library.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.0.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal, TYPE_CHECKING

from protobuf import Message
from protobuf._codegen import file_desc

from ... import validate_pb

if TYPE_CHECKING:
    from protobuf import DescFile


class IsHostname(Message[Literal["val"]]):
    """
    ```proto
    message buf.validate.conformance.cases.IsHostname
    ```

    Attributes:
        val:
            ```proto
            string val = 1;
            ```
    """

    __slots__ = ("val",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            val: str = "",
        ) -> None:
            pass

        val: str

class IsHostAndPort(Message[Literal["val", "port_required"]]):
    """
    ```proto
    message buf.validate.conformance.cases.IsHostAndPort
    ```

    Attributes:
        val:
            ```proto
            string val = 1;
            ```
        port_required:
            ```proto
            bool port_required = 2;
            ```
    """

    __slots__ = ("val", "port_required")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            val: str = "",
            port_required: bool = False,
        ) -> None:
            pass

        val: str
        port_required: bool

class IsIpPrefix(Message[Literal["val", "version", "strict"]]):
    """
    ```proto
    message buf.validate.conformance.cases.IsIpPrefix
    ```

    Attributes:
        val:
            ```proto
            string val = 1;
            ```
        version:
            ```proto
            optional int32 version = 2;
            ```
        strict:
            ```proto
            optional bool strict = 3;
            ```
    """

    __slots__ = ("val", "version", "strict")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            val: str = "",
            version: int | None = None,
            strict: bool | None = None,
        ) -> None:
            pass

        val: str
        version: int
        strict: bool

class IsIp(Message[Literal["val", "version"]]):
    """
    ```proto
    message buf.validate.conformance.cases.IsIp
    ```

    Attributes:
        val:
            ```proto
            string val = 1;
            ```
        version:
            ```proto
            optional int32 version = 2;
            ```
    """

    __slots__ = ("val", "version")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            val: str = "",
            version: int | None = None,
        ) -> None:
            pass

        val: str
        version: int

class IsEmail(Message[Literal["val"]]):
    """
    ```proto
    message buf.validate.conformance.cases.IsEmail
    ```

    Attributes:
        val:
            ```proto
            string val = 1;
            ```
    """

    __slots__ = ("val",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            val: str = "",
        ) -> None:
            pass

        val: str

class IsUri(Message[Literal["val"]]):
    """
    ```proto
    message buf.validate.conformance.cases.IsUri
    ```

    Attributes:
        val:
            ```proto
            string val = 1;
            ```
    """

    __slots__ = ("val",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            val: str = "",
        ) -> None:
            pass

        val: str

class IsUriRef(Message[Literal["val"]]):
    """
    ```proto
    message buf.validate.conformance.cases.IsUriRef
    ```

    Attributes:
        val:
            ```proto
            string val = 1;
            ```
    """

    __slots__ = ("val",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            val: str = "",
        ) -> None:
            pass

        val: str


_DESC = file_desc(
    b'\n,buf/validate/conformance/cases/library.proto\x12\x1ebuf.validate.conformance.cases\x1a\x1bbuf/validate/validate.proto"Q\n\nIsHostname\x12\x10\n\x03val\x18\x01 \x01(\tR\x03val:1\xbaH.\x1a,\n\x13library.is_hostname\x1a\x15this.val.isHostname()"\x93\x01\n\rIsHostAndPort\x12\x10\n\x03val\x18\x01 \x01(\tR\x03val\x12#\n\rport_required\x18\x02 \x01(\x08R\x0cportRequired:K\xbaHH\x1aF\n\x18library.is_host_and_port\x1a*this.val.isHostAndPort(this.port_required)"\xf0\x02\n\nIsIpPrefix\x12\x10\n\x03val\x18\x01 \x01(\tR\x03val\x12\x1d\n\x07version\x18\x02 \x01(\x05H\x00R\x07version\x88\x01\x01\x12\x1b\n\x06strict\x18\x03 \x01(\x08H\x01R\x06strict\x88\x01\x01B\n\n\x08_versionB\t\n\x07_strict:\xfc\x01\xbaH\xf8\x01\x1a\xf5\x01\n\x14library.is_ip_prefix\x1a\xdc\x01has(this.version) && has(this.strict) ? this.val.isIpPrefix(this.version, this.strict) : has(this.version) ? this.val.isIpPrefix(this.version) : has(this.strict) ? this.val.isIpPrefix(this.strict) : this.val.isIpPrefix()"\x9c\x01\n\x04IsIp\x12\x10\n\x03val\x18\x01 \x01(\tR\x03val\x12\x1d\n\x07version\x18\x02 \x01(\x05H\x00R\x07version\x88\x01\x01B\n\n\x08_version:W\xbaHT\x1aR\n\rlibrary.is_ip\x1aAhas(this.version) ? this.val.isIp(this.version) : this.val.isIp()"H\n\x07IsEmail\x12\x10\n\x03val\x18\x01 \x01(\tR\x03val:+\xbaH(\x1a&\n\x10library.is_email\x1a\x12this.val.isEmail()"B\n\x05IsUri\x12\x10\n\x03val\x18\x01 \x01(\tR\x03val:\'\xbaH$\x1a"\n\x0elibrary.is_uri\x1a\x10this.val.isUri()"L\n\x08IsUriRef\x12\x10\n\x03val\x18\x01 \x01(\tR\x03val:.\xbaH+\x1a)\n\x12library.is_uri_ref\x1a\x13this.val.isUriRef()b\x06proto3',
    [
        validate_pb.desc(),
    ],
    {
        "IsHostname": IsHostname,
        "IsHostAndPort": IsHostAndPort,
        "IsIpPrefix": IsIpPrefix,
        "IsIp": IsIp,
        "IsEmail": IsEmail,
        "IsUri": IsUri,
        "IsUriRef": IsUriRef,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `buf/validate/conformance/cases/library.proto`."""
    return _DESC
