# Generated from buf/validate/conformance/cases/wkt_nested.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.0.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal, TYPE_CHECKING

from protobuf import Message
from protobuf._codegen import file_desc

from ... import validate_pb

if TYPE_CHECKING:
    from protobuf import DescFile


class WktLevelOne(Message[Literal["two"]]):
    """
    ```proto
    message buf.validate.conformance.cases.WktLevelOne
    ```

    Attributes:
        two:
            ```proto
            optional buf.validate.conformance.cases.WktLevelOne.WktLevelTwo two = 1;
            ```
    """

    __slots__ = ("two",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            two: WktLevelOne.WktLevelTwo | None = None,
        ) -> None:
            pass

        two: WktLevelOne.WktLevelTwo | None

    class WktLevelTwo(Message[Literal["three"]]):
        """
        ```proto
        message buf.validate.conformance.cases.WktLevelOne.WktLevelTwo
        ```

        Attributes:
            three:
                ```proto
                optional buf.validate.conformance.cases.WktLevelOne.WktLevelTwo.WktLevelThree three = 1;
                ```
        """

        __slots__ = ("three",)

        if TYPE_CHECKING:

            def __init__(
                self,
                *,
                three: WktLevelOne.WktLevelTwo.WktLevelThree | None = None,
            ) -> None:
                pass

            three: WktLevelOne.WktLevelTwo.WktLevelThree | None

        class WktLevelThree(Message[Literal["uuid"]]):
            """
            ```proto
            message buf.validate.conformance.cases.WktLevelOne.WktLevelTwo.WktLevelThree
            ```

            Attributes:
                uuid:
                    ```proto
                    string uuid = 1;
                    ```
            """

            __slots__ = ("uuid",)

            if TYPE_CHECKING:

                def __init__(
                    self,
                    *,
                    uuid: str = "",
                ) -> None:
                    pass

                uuid: str


_DESC = file_desc(
    b'\n/buf/validate/conformance/cases/wkt_nested.proto\x12\x1ebuf.validate.conformance.cases\x1a\x1bbuf/validate/validate.proto"\x84\x02\n\x0bWktLevelOne\x12Q\n\x03two\x18\x01 \x01(\x0b27.buf.validate.conformance.cases.WktLevelOne.WktLevelTwoR\x03twoB\x06\xbaH\x03\xc8\x01\x01\x1a\xa1\x01\n\x0bWktLevelTwo\x12c\n\x05three\x18\x01 \x01(\x0b2E.buf.validate.conformance.cases.WktLevelOne.WktLevelTwo.WktLevelThreeR\x05threeB\x06\xbaH\x03\xc8\x01\x01\x1a-\n\rWktLevelThree\x12\x1c\n\x04uuid\x18\x01 \x01(\tR\x04uuidB\x08\xbaH\x05r\x03\xb0\x01\x01b\x06proto3',
    [
        validate_pb.desc(),
    ],
    {
        "WktLevelOne": WktLevelOne,
        "WktLevelOne.WktLevelTwo": WktLevelOne.WktLevelTwo,
        "WktLevelOne.WktLevelTwo.WktLevelThree": WktLevelOne.WktLevelTwo.WktLevelThree,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `buf/validate/conformance/cases/wkt_nested.proto`."""
    return _DESC
