# Generated from buf/validate/conformance/cases/wkt_field_mask.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.0.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal, TYPE_CHECKING

from protobuf import Message
from protobuf._codegen import file_desc
from protobuf.wkt import field_mask_pb

from ... import validate_pb

if TYPE_CHECKING:
    from protobuf import DescFile
    from protobuf.wkt import FieldMask


class FieldMaskNone(Message[Literal["val"]]):
    """
    ```proto
    message buf.validate.conformance.cases.FieldMaskNone
    ```

    Attributes:
        val:
            ```proto
            optional google.protobuf.FieldMask val = 1;
            ```
    """

    __slots__ = ("val",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            val: FieldMask | None = None,
        ) -> None:
            pass

        val: FieldMask | None

class FieldMaskRequired(Message[Literal["val"]]):
    """
    ```proto
    message buf.validate.conformance.cases.FieldMaskRequired
    ```

    Attributes:
        val:
            ```proto
            optional google.protobuf.FieldMask val = 1;
            ```
    """

    __slots__ = ("val",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            val: FieldMask | None = None,
        ) -> None:
            pass

        val: FieldMask | None

class FieldMaskConst(Message[Literal["val"]]):
    """
    ```proto
    message buf.validate.conformance.cases.FieldMaskConst
    ```

    Attributes:
        val:
            ```proto
            optional google.protobuf.FieldMask val = 1;
            ```
    """

    __slots__ = ("val",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            val: FieldMask | None = None,
        ) -> None:
            pass

        val: FieldMask | None

class FieldMaskIn(Message[Literal["val"]]):
    """
    ```proto
    message buf.validate.conformance.cases.FieldMaskIn
    ```

    Attributes:
        val:
            ```proto
            optional google.protobuf.FieldMask val = 1;
            ```
    """

    __slots__ = ("val",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            val: FieldMask | None = None,
        ) -> None:
            pass

        val: FieldMask | None

class FieldMaskNotIn(Message[Literal["val"]]):
    """
    ```proto
    message buf.validate.conformance.cases.FieldMaskNotIn
    ```

    Attributes:
        val:
            ```proto
            optional google.protobuf.FieldMask val = 1;
            ```
    """

    __slots__ = ("val",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            val: FieldMask | None = None,
        ) -> None:
            pass

        val: FieldMask | None

class FieldMaskExample(Message[Literal["val"]]):
    """
    ```proto
    message buf.validate.conformance.cases.FieldMaskExample
    ```

    Attributes:
        val:
            ```proto
            optional google.protobuf.FieldMask val = 1;
            ```
    """

    __slots__ = ("val",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            val: FieldMask | None = None,
        ) -> None:
            pass

        val: FieldMask | None


_DESC = file_desc(
    b'\n3buf/validate/conformance/cases/wkt_field_mask.proto\x12\x1ebuf.validate.conformance.cases\x1a\x1bbuf/validate/validate.proto\x1a google/protobuf/field_mask.proto"=\n\rFieldMaskNone\x12,\n\x03val\x18\x01 \x01(\x0b2\x1a.google.protobuf.FieldMaskR\x03val"I\n\x11FieldMaskRequired\x124\n\x03val\x18\x01 \x01(\x0b2\x1a.google.protobuf.FieldMaskR\x03valB\x06\xbaH\x03\xc8\x01\x01"K\n\x0eFieldMaskConst\x129\n\x03val\x18\x01 \x01(\x0b2\x1a.google.protobuf.FieldMaskR\x03valB\x0b\xbaH\x08\xe2\x01\x05\n\x03\n\x01a"I\n\x0bFieldMaskIn\x12:\n\x03val\x18\x01 \x01(\x0b2\x1a.google.protobuf.FieldMaskR\x03valB\x0c\xbaH\t\xe2\x01\x06\x12\x01a\x12\x01b"L\n\x0eFieldMaskNotIn\x12:\n\x03val\x18\x01 \x01(\x0b2\x1a.google.protobuf.FieldMaskR\x03valB\x0c\xbaH\t\xe2\x01\x06\x1a\x01c\x1a\x01d"M\n\x10FieldMaskExample\x129\n\x03val\x18\x01 \x01(\x0b2\x1a.google.protobuf.FieldMaskR\x03valB\x0b\xbaH\x08\xe2\x01\x05"\x03\n\x01ab\x06proto3',
    [
        validate_pb.desc(),
        field_mask_pb.desc(),
    ],
    {
        "FieldMaskNone": FieldMaskNone,
        "FieldMaskRequired": FieldMaskRequired,
        "FieldMaskConst": FieldMaskConst,
        "FieldMaskIn": FieldMaskIn,
        "FieldMaskNotIn": FieldMaskNotIn,
        "FieldMaskExample": FieldMaskExample,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `buf/validate/conformance/cases/wkt_field_mask.proto`."""
    return _DESC
