# Generated from buf/validate/conformance/cases/wkt_wrappers.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.0.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal, TYPE_CHECKING

from protobuf import Message
from protobuf._codegen import file_desc
from protobuf.wkt import wrappers_pb

from ... import validate_pb

if TYPE_CHECKING:
    from protobuf import DescFile
    from protobuf.wkt import BoolValue, BytesValue, DoubleValue, FloatValue, Int32Value, Int64Value, StringValue, UInt32Value, UInt64Value


class WrapperNone(Message[Literal["val"]]):
    """
    ```proto
    message buf.validate.conformance.cases.WrapperNone
    ```

    Attributes:
        val:
            ```proto
            optional google.protobuf.Int32Value val = 1;
            ```
    """

    __slots__ = ("val",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            val: Int32Value | None = None,
        ) -> None:
            pass

        val: Int32Value | None

class WrapperFloat(Message[Literal["val"]]):
    """
    ```proto
    message buf.validate.conformance.cases.WrapperFloat
    ```

    Attributes:
        val:
            ```proto
            optional google.protobuf.FloatValue val = 1;
            ```
    """

    __slots__ = ("val",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            val: FloatValue | None = None,
        ) -> None:
            pass

        val: FloatValue | None

class WrapperDouble(Message[Literal["val"]]):
    """
    ```proto
    message buf.validate.conformance.cases.WrapperDouble
    ```

    Attributes:
        val:
            ```proto
            optional google.protobuf.DoubleValue val = 1;
            ```
    """

    __slots__ = ("val",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            val: DoubleValue | None = None,
        ) -> None:
            pass

        val: DoubleValue | None

class WrapperInt64(Message[Literal["val"]]):
    """
    ```proto
    message buf.validate.conformance.cases.WrapperInt64
    ```

    Attributes:
        val:
            ```proto
            optional google.protobuf.Int64Value val = 1;
            ```
    """

    __slots__ = ("val",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            val: Int64Value | None = None,
        ) -> None:
            pass

        val: Int64Value | None

class WrapperInt32(Message[Literal["val"]]):
    """
    ```proto
    message buf.validate.conformance.cases.WrapperInt32
    ```

    Attributes:
        val:
            ```proto
            optional google.protobuf.Int32Value val = 1;
            ```
    """

    __slots__ = ("val",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            val: Int32Value | None = None,
        ) -> None:
            pass

        val: Int32Value | None

class WrapperUInt64(Message[Literal["val"]]):
    """
    ```proto
    message buf.validate.conformance.cases.WrapperUInt64
    ```

    Attributes:
        val:
            ```proto
            optional google.protobuf.UInt64Value val = 1;
            ```
    """

    __slots__ = ("val",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            val: UInt64Value | None = None,
        ) -> None:
            pass

        val: UInt64Value | None

class WrapperUInt32(Message[Literal["val"]]):
    """
    ```proto
    message buf.validate.conformance.cases.WrapperUInt32
    ```

    Attributes:
        val:
            ```proto
            optional google.protobuf.UInt32Value val = 1;
            ```
    """

    __slots__ = ("val",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            val: UInt32Value | None = None,
        ) -> None:
            pass

        val: UInt32Value | None

class WrapperBool(Message[Literal["val"]]):
    """
    ```proto
    message buf.validate.conformance.cases.WrapperBool
    ```

    Attributes:
        val:
            ```proto
            optional google.protobuf.BoolValue val = 1;
            ```
    """

    __slots__ = ("val",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            val: BoolValue | None = None,
        ) -> None:
            pass

        val: BoolValue | None

class WrapperString(Message[Literal["val"]]):
    """
    ```proto
    message buf.validate.conformance.cases.WrapperString
    ```

    Attributes:
        val:
            ```proto
            optional google.protobuf.StringValue val = 1;
            ```
    """

    __slots__ = ("val",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            val: StringValue | None = None,
        ) -> None:
            pass

        val: StringValue | None

class WrapperBytes(Message[Literal["val"]]):
    """
    ```proto
    message buf.validate.conformance.cases.WrapperBytes
    ```

    Attributes:
        val:
            ```proto
            optional google.protobuf.BytesValue val = 1;
            ```
    """

    __slots__ = ("val",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            val: BytesValue | None = None,
        ) -> None:
            pass

        val: BytesValue | None

class WrapperRequiredString(Message[Literal["val"]]):
    """
    ```proto
    message buf.validate.conformance.cases.WrapperRequiredString
    ```

    Attributes:
        val:
            ```proto
            optional google.protobuf.StringValue val = 1;
            ```
    """

    __slots__ = ("val",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            val: StringValue | None = None,
        ) -> None:
            pass

        val: StringValue | None

class WrapperRequiredEmptyString(Message[Literal["val"]]):
    """
    ```proto
    message buf.validate.conformance.cases.WrapperRequiredEmptyString
    ```

    Attributes:
        val:
            ```proto
            optional google.protobuf.StringValue val = 1;
            ```
    """

    __slots__ = ("val",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            val: StringValue | None = None,
        ) -> None:
            pass

        val: StringValue | None

class WrapperOptionalUuidString(Message[Literal["val"]]):
    """
    ```proto
    message buf.validate.conformance.cases.WrapperOptionalUuidString
    ```

    Attributes:
        val:
            ```proto
            optional google.protobuf.StringValue val = 1;
            ```
    """

    __slots__ = ("val",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            val: StringValue | None = None,
        ) -> None:
            pass

        val: StringValue | None

class WrapperRequiredFloat(Message[Literal["val"]]):
    """
    ```proto
    message buf.validate.conformance.cases.WrapperRequiredFloat
    ```

    Attributes:
        val:
            ```proto
            optional google.protobuf.FloatValue val = 1;
            ```
    """

    __slots__ = ("val",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            val: FloatValue | None = None,
        ) -> None:
            pass

        val: FloatValue | None


_DESC = file_desc(
    b'\n1buf/validate/conformance/cases/wkt_wrappers.proto\x12\x1ebuf.validate.conformance.cases\x1a\x1bbuf/validate/validate.proto\x1a\x1egoogle/protobuf/wrappers.proto"<\n\x0bWrapperNone\x12-\n\x03val\x18\x01 \x01(\x0b2\x1b.google.protobuf.Int32ValueR\x03val"I\n\x0cWrapperFloat\x129\n\x03val\x18\x01 \x01(\x0b2\x1b.google.protobuf.FloatValueR\x03valB\n\xbaH\x07\n\x05%\x00\x00\x00\x00"O\n\rWrapperDouble\x12>\n\x03val\x18\x01 \x01(\x0b2\x1c.google.protobuf.DoubleValueR\x03valB\x0e\xbaH\x0b\x12\t!\x00\x00\x00\x00\x00\x00\x00\x00"F\n\x0cWrapperInt64\x126\n\x03val\x18\x01 \x01(\x0b2\x1b.google.protobuf.Int64ValueR\x03valB\x07\xbaH\x04"\x02 \x00"F\n\x0cWrapperInt32\x126\n\x03val\x18\x01 \x01(\x0b2\x1b.google.protobuf.Int32ValueR\x03valB\x07\xbaH\x04\x1a\x02 \x00"H\n\rWrapperUInt64\x127\n\x03val\x18\x01 \x01(\x0b2\x1c.google.protobuf.UInt64ValueR\x03valB\x07\xbaH\x042\x02 \x00"H\n\rWrapperUInt32\x127\n\x03val\x18\x01 \x01(\x0b2\x1c.google.protobuf.UInt32ValueR\x03valB\x07\xbaH\x04*\x02 \x00"D\n\x0bWrapperBool\x125\n\x03val\x18\x01 \x01(\x0b2\x1a.google.protobuf.BoolValueR\x03valB\x07\xbaH\x04j\x02\x08\x01"K\n\rWrapperString\x12:\n\x03val\x18\x01 \x01(\x0b2\x1c.google.protobuf.StringValueR\x03valB\n\xbaH\x07r\x05B\x03bar"F\n\x0cWrapperBytes\x126\n\x03val\x18\x01 \x01(\x0b2\x1b.google.protobuf.BytesValueR\x03valB\x07\xbaH\x04z\x02\x10\x03"V\n\x15WrapperRequiredString\x12=\n\x03val\x18\x01 \x01(\x0b2\x1c.google.protobuf.StringValueR\x03valB\r\xbaH\n\xc8\x01\x01r\x05\n\x03bar"X\n\x1aWrapperRequiredEmptyString\x12:\n\x03val\x18\x01 \x01(\x0b2\x1c.google.protobuf.StringValueR\x03valB\n\xbaH\x07\xc8\x01\x01r\x02\n\x00"X\n\x19WrapperOptionalUuidString\x12;\n\x03val\x18\x01 \x01(\x0b2\x1c.google.protobuf.StringValueR\x03valB\x0b\xbaH\x08\xc8\x01\x00r\x03\xb0\x01\x01"T\n\x14WrapperRequiredFloat\x12<\n\x03val\x18\x01 \x01(\x0b2\x1b.google.protobuf.FloatValueR\x03valB\r\xbaH\n\xc8\x01\x01\n\x05%\x00\x00\x00\x00b\x06proto3',
    [
        validate_pb.desc(),
        wrappers_pb.desc(),
    ],
    {
        "WrapperNone": WrapperNone,
        "WrapperFloat": WrapperFloat,
        "WrapperDouble": WrapperDouble,
        "WrapperInt64": WrapperInt64,
        "WrapperInt32": WrapperInt32,
        "WrapperUInt64": WrapperUInt64,
        "WrapperUInt32": WrapperUInt32,
        "WrapperBool": WrapperBool,
        "WrapperString": WrapperString,
        "WrapperBytes": WrapperBytes,
        "WrapperRequiredString": WrapperRequiredString,
        "WrapperRequiredEmptyString": WrapperRequiredEmptyString,
        "WrapperOptionalUuidString": WrapperOptionalUuidString,
        "WrapperRequiredFloat": WrapperRequiredFloat,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `buf/validate/conformance/cases/wkt_wrappers.proto`."""
    return _DESC
